Feature 2-
Ali-0111/Microverse_Portfolio pull request #3
Opened 2023-01-13 22:02 UTC by Ali-0111

2023-01-15 01:54 UTC, wayungi requested changes
Hi @Ali-0111 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![image](https://user-images.githubusercontent.com/99656687/212510519-85f7575b-c347-461d-ba0f-b334036471c9.png)


## Highlights
- Good PR title ✔️ 
- Good PR description ✔️ 
- Professional README ✔️ 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- [ OPTIONAL] Please write descriptive commit messages in the imperative tense. For example **_Add padding-top  to footer_** instead of **_completedfooter_**
Hi <STUDENT_MENTION>, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._  

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-15 01:54 UTC, wayungi commented on index.html
> +          </div>
- [ ] Please make sure the technologies are in `<li>` tags. The `<li>`  tags should be in a `<ul>`  tag.  Check the example below. Apply this to instances of technologies

```
<ul>
  <li>HTML/CSS</li>
  ....
</ul>
```
![inst 1](https://user-images.githubusercontent.com/99656687/212503848-516890bd-1bd0-4077-a79c-a940d22c94ae.png)

2023-01-15 01:54 UTC, wayungi commented on index.html
> +      </button>
- [ ] Please use either a `<button>` or `<a>` tag but not both. It is semantically incorrect to use both in this manner

2023-01-15 01:54 UTC, wayungi commented on index.html
> +      </button>
- [ ] Your button currently does not respond to different states, please add the button states as required. 

![states](https://user-images.githubusercontent.com/99656687/212505283-d3ae8c72-cb67-49fc-819b-b82ae514329e.png)

2023-01-15 01:54 UTC, wayungi commented on index.html
> +        <h2>Skills</h2>
The technology categories Language,Framework and skills should be list items in a `<ul>` tag.
![finale](https://user-images.githubusercontent.com/99656687/212508559-47c51fcb-fcc4-4650-992a-d49b7c644100.png)

2023-01-15 01:54 UTC, wayungi commented on index.html
> +        <h2>Skills</h2>
- [ ] Align the content with flex box please.

2023-01-15 11:23 UTC, Ali-0111 commented
I need your help. can you manage for me a zoom meeting?

On Sun, Jan 15, 2023 at 6:24 AM Francis Wayungi ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @Ali-0111 <https://github.com/Ali-0111> ,
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> [image: image]
> <https://user-images.githubusercontent.com/99656687/212510519-85f7575b-c347-461d-ba0f-b334036471c9.png>
> Highlights
>
>    - Good PR title ✔️
>    - Good PR description ✔️
>    - Professional README ✔️
>
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
>    - [ OPTIONAL] Please write descriptive commit messages in the
>    imperative tense. For example *Add padding-top to footer* instead of
>    *completedfooter*
>    Hi <STUDENT_MENTION>,
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> Highlights Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In style.css
> <https://github.com/Ali-0111/Microverse_Portfolio/pull/3#discussion_r1070468409>
> :
>
> > +.work {
>
> +  width: 100%;
>
> +}
>
>
>
>    - Please apply a display property of grid to this element. Elements
>    inside this section must be laid by grid property.
>    [image: req1]
>    <https://user-images.githubusercontent.com/99656687/212503195-1ccf4196-9024-44f9-816a-e0c399838045.png>
>
> ------------------------------
>
> In style.css
> <https://github.com/Ali-0111/Microverse_Portfolio/pull/3#discussion_r1070468984>
> :
>
> > +.grid_2r {
>
> +  display: grid;
>
> +  grid-template-rows: 18.6rem auto;
>
> +  grid-column: 1fr;
>
> +}
>
>
>
>    - Please apply the display flex property here. The requirement says
>    align the content of each individual card with flex box.
>    [image: req1]
>    <https://user-images.githubusercontent.com/99656687/212503553-50b803b0-272d-4062-aed0-0a14b74a18a3.png>
>
> ------------------------------
>
> In index.html
> <https://github.com/Ali-0111/Microverse_Portfolio/pull/3#discussion_r1070470097>
> :
>
> > +          <div class="btns">
>
> +            <button class="btn-1 btn">HTML/CSS</button>
>
> +            <button class="btn-2 btn">Ruby on Rails</button>
>
> +            <button class="btn-3 btn">JavaScript</button>
>
> +            <button class="btn-4">
>
> +              <a href="#">See this project</a>
>
> +              <span class="icon"></span>
>
> +          </button>
>
> +          </div>
>
>
>
>    - Please make sure the technologies are in <li> tags. The <li> tags
>    should be in a <ul> tag. Check the example below. Apply this to
>    instances of technologies
>
> <ul>
>
>   <li>HTML/CSS</li>
>
>   ....
>
> </ul>
>
>
> [image: inst 1]
> <https://user-images.githubusercontent.com/99656687/212503848-516890bd-1bd0-4077-a79c-a940d22c94ae.png>
> ------------------------------
>
> In index.html
> <https://github.com/Ali-0111/Microverse_Portfolio/pull/3#discussion_r1070472746>
> :
>
> > +      <button class="footer-btn">
>
> +        Get my Resume
>
> +        <span class="footer-down"></span>
>
> +      </button>
>
>
>
>    - Please use either a <button> or <a> tag but not both. It is
>    semantically incorrect to use both in this manner
>
> ------------------------------
>
> In index.html
> <https://github.com/Ali-0111/Microverse_Portfolio/pull/3#discussion_r1070475528>
> :
>
> > +        <h2>Languages</h2>
>
> +        <ul>
>
> +          <li>JavaScript (ES5/ES6)</li>
>
> +          <li>Ruby</li>
>
> +          <li>Html</li>
>
> +          <li>Css</li>
>
> +        </ul>
>
> +        <div class="imgbtm flex-end">
>
> +       </div>
>
> +      </article>
>
> +      <article class="text-about red">
>
> +        <h2>FrameWorks</h2>
>
> +        <ul>
>
> +          <li>Bootstrap</li>
>
> +          <li>Ruby on Rails</li>
>
> +          <li>RSpec</li>
>
> +          <li>Capibara</li>
>
> +          <li>Selenium</li>
>
> +        </ul>
>
> +        <div class="imgbtm2 flex-end">
>
> +       </div>
>
> +      </article>
>
> +      <article class="text-about yellow">
>
> +        <h2>Skills</h2>
>
>
> The technology categories Language,Framework and skills should be list
> items in a <ul> tag.
> [image: finale]
> <https://user-images.githubusercontent.com/99656687/212508559-47c51fcb-fcc4-4650-992a-d49b7c644100.png>
> ------------------------------
>
> In index.html
> <https://github.com/Ali-0111/Microverse_Portfolio/pull/3#discussion_r1070473958>
> :
>
> > +      <button class="footer-btn">
>
> +        Get my Resume
>
> +        <span class="footer-down"></span>
>
> +      </button>
>
>
>
>    - Your button currently does not respond to different states, please
>    add the button states as required.
>
> [image: states]
> <https://user-images.githubusercontent.com/99656687/212505283-d3ae8c72-cb67-49fc-819b-b82ae514329e.png>
> ------------------------------
>
> In index.html
> <https://github.com/Ali-0111/Microverse_Portfolio/pull/3#discussion_r1070475700>
> :
>
> > +        <h2>Languages</h2>
>
> +        <ul>
>
> +          <li>JavaScript (ES5/ES6)</li>
>
> +          <li>Ruby</li>
>
> +          <li>Html</li>
>
> +          <li>Css</li>
>
> +        </ul>
>
> +        <div class="imgbtm flex-end">
>
> +       </div>
>
> +      </article>
>
> +      <article class="text-about red">
>
> +        <h2>FrameWorks</h2>
>
> +        <ul>
>
> +          <li>Bootstrap</li>
>
> +          <li>Ruby on Rails</li>
>
> +          <li>RSpec</li>
>
> +          <li>Capibara</li>
>
> +          <li>Selenium</li>
>
> +        </ul>
>
> +        <div class="imgbtm2 flex-end">
>
> +       </div>
>
> +      </article>
>
> +      <article class="text-about yellow">
>
> +        <h2>Skills</h2>
>
>
>
>    - Align the content with flex box please.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Ali-0111/Microverse_ [...]

2023-01-15 11:31 UTC, Ali-0111 commented
Hi @wayungi, can you manage a zoom meeting . I need your help

2023-01-18 14:51 UTC, Ali-0111 commented
how to use css grid with work section? I did it, but i think it has problem. please focus more on this

2023-01-18 16:12 UTC, ABDULALI3468 requested changes
# Changes Required 👍 

Hi @Ali-0111 , 

<img src="https://media1.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

Great work on making the changes requested by a previous reviewer 👏 
You've done really well implementing some of the requested changes, but there are still some which aren't been addressed yet.


## Highlights 
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.


 ## Required Changes ♻️

 **_Check the comments below to see the changes required._**


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: ![GitHub followers](https://img.shields.io/github/followers/ABDULALI3468?label=ABDULALI&style=social)
> * This is My **Linkedin**: [![Linkedin Badge](https://img.shields.io/badge/-ABDUL%20ALI-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/abdul-ali-5400bb216/)](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [![Twitter Badge](https://img.shields.io/badge/-@mrabdul_ali_-1ca0f1?style=flat-square&labelColor=1ca0f1&logo=twitter&logoColor=white&link=https://twitter.com/mrabdul_ali)](https://twitter.com/mrabdul_ali)&nbsp;

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 16:12 UTC, ABDULALI3468 commented on index.html
> +      </header>
The font used in the Figma Design is named `Playfair Display`. Please consider matching your current font with the design as it's the project requirement to make the design exactly like the Template you choose. You can excess the font using [Google Fonts](https://fonts.google.com/specimen/Playfair+Display?query=+Playfair+Display).

Moreover the top and bottom margins are not similar to the design also. Consider reviewing them.

2023-01-20 06:55 UTC, NahnahAJ requested changes
Hi @Ali-0111 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which haven't been addressed yet.
<img src="https://media0.giphy.com/media/h7u3pLvYK3HfQ4yXxW/giphy.gif"/>

 ## Highlights
- Good PR request :heavy_check_mark: 
- Professional README :heavy_check_mark: 
- Good use of GitHub flow. :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 06:55 UTC, NahnahAJ commented on index.html
> +        </button>
- [ ] Just as the previous reviewer mentioned, kindly ensure that the icon in your `cv-btn` is showing cause it's still the same as you sent for review before. Kindly fix this so you can meet all the project requirements and also so your design can look like that of the Figma Design. :100: 
- Your Design
![image](https://user-images.githubusercontent.com/102699958/213633459-1010ace8-1d25-40f7-b17a-fef6235eb0b2.png)

- The Figma Design
![image](https://user-images.githubusercontent.com/102699958/213633550-47cf4113-d8f2-4c7e-a48d-448a5f2f5e6a.png)

- [ ] It is also missing the button interaction styles just as the previous reviewer mentioned. Please consider adding the `hover` and `pressed` effects on these buttons as well just as you did for the other buttons. It will make your styles according to the design. :+1:

2023-01-20 06:55 UTC, NahnahAJ commented on index.html
> +          <li>Css</li>
- [ ] Just as the previous reviewer mentioned earlier, please consider adding a `margin-top: 16px` on all of the lists to make it in accordance with the Figma Design. Currently, it looks different from the Figma design. So kindly fix this so you can meet all the project requirements.

- Your Design
![image](https://user-images.githubusercontent.com/102699958/213634557-f56b3253-e2df-4d68-aa15-5cc2da65a1a1.png)

- The Figma Design
![image](https://user-images.githubusercontent.com/102699958/213634444-7765f35b-bf7a-44ae-bfe5-dc8a899d68fe.png)

2023-01-20 09:43 UTC, Ali-0111 commented
I could not apply hover state while button has span and div tags. can you
help me? can you provide me a zoom call?


On Fri, Jan 20, 2023 at 11:25 AM Felicia G. Awuah ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @Ali-0111 <https://github.com/Ali-0111> ,
>
> Great work on making the changes requested by a previous reviewer 👏
> You've done well implementing some of the requested changes, but there are
> still some which haven't been addressed yet.
>
> <https://camo.githubusercontent.com/2ed9e3af6ae0f6320069b47497aac04bcd3b714e9fb31a07f71ffe71a82b5896/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f68377533704c76594b3348665134795878572f67697068792e676966>
> Highlights
>
>    - Good PR request ✔️
>    - Professional README ✔️
>    - Good use of GitHub flow. ✔️
>
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me @NahnahAJ <https://github.com/NahnahAJ> in
> your question so I can receive the notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/Ali-0111/Microverse_Portfolio/pull/3#discussion_r1082154129>
> :
>
> > +        <button class="cv-btn">
>
> +          <a href="#">Get my CV</a>
>
> +          <span class="downbtn"></span>
>
> +        </button>
>
>
>
>    -
>
>    Just as the previous reviewer mentioned, kindly ensure that the icon
>    in your cv-btn is showing cause it's still the same as you sent for
>    review before. Kindly fix this so you can meet all the project requirements
>    and also so your design can look like that of the Figma Design. 💯
>    -
>
>    Your Design
>    [image: image]
>    <https://user-images.githubusercontent.com/102699958/213633459-1010ace8-1d25-40f7-b17a-fef6235eb0b2.png>
>    -
>
>    The Figma Design
>    [image: image]
>    <https://user-images.githubusercontent.com/102699958/213633550-47cf4113-d8f2-4c7e-a48d-448a5f2f5e6a.png>
>    -
>
>    It is also missing the button interaction styles just as the previous
>    reviewer mentioned. Please consider adding the hover and pressed
>    effects on these buttons as well just as you did for the other buttons. It
>    will make your styles according to the design. 👍
>
> ------------------------------
>
> In index.html
> <https://github.com/Ali-0111/Microverse_Portfolio/pull/3#discussion_r1082157361>
> :
>
> > +          <li>JavaScript (ES5/ES6)</li>
>
> +          <li>Ruby</li>
>
> +          <li>Html</li>
>
> +          <li>Css</li>
>
>
>
>    -
>
>    Just as the previous reviewer mentioned earlier, please consider
>    adding a margin-top: 16px on all of the lists to make it in accordance
>    with the Figma Design. Currently, it looks different from the Figma design.
>    So kindly fix this so you can meet all the project requirements.
>    -
>
>    Your Design
>    [image: image]
>    <https://user-images.githubusercontent.com/102699958/213634557-f56b3253-e2df-4d68-aa15-5cc2da65a1a1.png>
>    -
>
>    The Figma Design
>    [image: image]
>    <https://user-images.githubusercontent.com/102699958/213634444-7765f35b-bf7a-44ae-bfe5-dc8a899d68fe.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Ali-0111/Microverse_Portfolio/pull/3#pullrequestreview-1263030881>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARRMIX6SQO3DKK3YN2WGZODWTIZGJANCNFSM6AAAAAAT23NH2I>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-20 09:48 UTC, NahnahAJ commented
Alright. You can join this call
<https://microverse.zoom.us/j/3249935048?pwd=QjVEZUo3WWd4bnJucWpmVWhVeHRlQT09#success>

2023-01-20 11:50 UTC, osamaashraf6 approved these changes
Hi @Ali-0111  , 
# STATUS: APPROVED! 🥇🟢🟢💯 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :ship it: 
Congratulations! 🎉 

## Highlights💯🎈🪄✔️

- [x] Descriptive READme file in a professional way.✔️
- [x] No linter errors. ✔️
- [x] Good usage in correcting GitHub flow.✔️
- [x] Nice design.✔️



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 14:02 UTC, merged